### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by drc007** [srijitseal/DILI_Predictor#2]
Hi,

I get this error when I try installing

Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/chrisswain/miniconda3/envs/DILIpredition/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/chrisswain/miniconda3/envs/DILIpredition/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/chrisswain/miniconda3/envs/DILIpredition/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Users/chrisswain/miniconda3/envs/DILIpredition/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/chrisswain/miniconda3/envs/DILIpredition/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/4h/_8pw3vdd7hvbzj3p87symg0r0000gn/T/pip-build-env-k7u_ho1o/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/4h/_8pw3vdd7hvbzj3p87symg0r0000gn/T/pip-build-env-k7u_ho1o/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/4h/_8pw3vdd7hvbzj3p87symg0r0000gn/T/pip-build-env-k7u_ho1o/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by srijitseal** [comment]
Hi Chris,

This is because of changes in python 3.12 after this software was developed.

Can you try Python <3.12, >=3.9

Best,
Srijit

**Comment by drc007** [comment]
Hi,

That worked!

Well at least the help message displays ;-)

Cheers

Chris

**Comment by srijitseal** [comment]
Let us know what you think about it! 
seal@broadinstitute.org :D

**Comment by drc007** [comment]
Seems to be working!


(DILIpred) ***@***.*** ~ % dilipred -smiles "O=C(CNC1=CC=CC=C1)NC1=CC=CC=C1"

██████████   █████ █████       █████ ███████████                         █████
░░███░░░░███ ░░███ ░░███       ░░███ ░░███░░░░░███                       ░░███
 ░███   ░░███ ░███  ░███        ░███  ░███    ░███ ████████   ██████   ███████
 ░███    ░███ ░███  ░███        ░███  ░██████████ ░░███░░███ ███░░███ ███░░███
 ░███    ░███ ░███  ░███        ░███  ░███░░░░░░   ░███ ░░░ ░███████ ░███ ░███
 ░███    ███  ░███  ░███      █ ░███  ░███         ░███     ░███░░░  ░███ ░███
 ██████████   █████ ███████████ █████ █████        █████    ░░██████ ░░████████
░░░░░░░░░░   ░░░░░ ░░░░░░░░░░░ ░░░░░ ░░░░░        ░░░░░      ░░░░░░   ░░░░░░░░


If you use DILIPred in your work, please cite:
Improved Detection of Drug-Induced Liver Injury by Integrating Predicted In Vivo and In Vitro Data
Srijit Seal, Dominic Williams, Layla Hosseini-Gerami, Manas Mahale, Anne E. Carpenter, Ola Spjuth,
and Andreas Bender
doi: https://doi.org/10.1021/acs.chemrestox.4c00015

100%|██████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.07it/s]
2024-07-11 21:32:55.362 | CRITICAL | dilipred.main:predict:458 - The compound is predicted DILI-Positive
(DILIpred) ***@***.*** ~ %
